Upgrade Decidim to v0.20
CodiTramuntana/decidim-sitges-app pull request #32
Opened 2021-06-11 07:58 UTC by LauraJaimeC

- Upgrade Decidim to v0.20

2021-06-14 07:42 UTC, tramuntanal requested changes
Hi @LauraJaimeC ,
Please remember to always link the changelog for the corresponding version:
https://github.com/decidim/decidim/blob/release/0.20-stable/CHANGELOG.md

From this changelog, remember that we need to change the geocoder configuration, and apply the searchable indexing as stated here: https://github.com/decidim/decidim/blob/release/0.20-stable/CHANGELOG.md#decidimsearchable

2021-06-14 07:42 UTC, tramuntanal commented on Gemfile
> +DECIDIM_VERSION = { git: 'https://github.com/decidim/decidim.git', branch: 'release/0.20-stable' }
use CodiTramuntana's fork

2021-06-15 06:07 UTC, LauraJaimeC commented on Gemfile
> +DECIDIM_VERSION = { git: 'https://github.com/decidim/decidim.git', branch: 'release/0.20-stable' }
In our fork don't have release 0.20. Do I create the branch?

2021-06-15 06:33 UTC, LauraJaimeC commented on Gemfile
> +DECIDIM_VERSION = { git: 'https://github.com/decidim/decidim.git', branch: 'release/0.20-stable' }
done!

2021-06-15 14:31 UTC, LauraJaimeC commented
Closed in favor of https://github.com/CodiTramuntana/decidim-sitges-app/pull/37

2021-06-15 14:31 UTC, closed without merging